name: code style

on:
  push:
    paths:
      - '**.php'
      - 'pint.json'
  pull_request:
    paths:
      - '**.php'
      - 'pint.json'

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Cache Composer dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.composer/cache/files
          key: composer-cs-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-cs-

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Check code style
        run: vendor/bin/pint --test
